pipeline{
    stages{
    //部署到kubernetes
    stage('Deploy to K8s') {
         steps{
         if(env.ENV == 'dev')
            {
            sh ./k8s/my_deploy.sh ${env.ENV}
            }
         else{
            sh ./k8s/my_deploy.sh
        }
        }
    }
    }
}